apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: grafana
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: grafana
    targetRevision: 12.7.1   # latest chart version
    helm:
      valueFiles:
        - values.yaml   # keep your values separate

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
