apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: grafana
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: grafana
    targetRevision: 12.7.1

    helm:
      values: |
        adminUser: admin
        adminPassword: admin123

        service:
          type: ClusterIP

        persistence:
          enabled: true
          storageClassName: gp3
          size: 10Gi       

        grafana.ini:
          server:
            root_url: "%(protocol)s://%(domain)s/"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
