admin:
  existingSecret: grafana-admin-secret
  userKey: admin-user
  passwordKey: admin-password

service:
  type: ClusterIP

persistence:
  enabled: true
  storageClassName: gp3
  size: 10Gi

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/"