apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets/application.yaml
  - external-secrets/secretstore.yaml
  - external-secrets/test-secret.yaml
  - aws-load-balancer-controller/application.yaml
  - external-dns/application.yaml