apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ebs-csi-driver
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: 2.62.0   # latest chart version
    helm:
      values: |
        controller:
          serviceAccount:
            create: true
            name: ebs-csi-controller-sa
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::219834006508:role/retail-platform-dev-ebs-csi-role

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
