apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: test-secret
  namespace: external-secrets

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: test-secret

  data:
    - secretKey: username
      remoteRef:
        key: retail-platform/dev/test-secret
        property: username

    - secretKey: password
      remoteRef:
        key: retail-platform/dev/test-secret
        property: password