apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - trivy/application.yaml
  - kyverno/application.yaml
  - kyverno-policies/require-labels.yaml
  - kyverno-policies/require-resources.yaml
  - kyverno-policies/disallow-latest-tag.yaml